#!/usr/bin/env python3
"""Download and audit the exact PLUE/MNLI corpus used by the NLI spike.

Everything generated by this script lives under ``build/`` and is disposable.
The script deliberately does not read the adversarial Spike 7 set: that set
must stay sealed until model selection is finished on PLUE validation data.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
import sys
import urllib.request
import zipfile
from collections import Counter
from pathlib import Path


RELEASE_URL = "https://github.com/ju-resplande/PLUE/releases/download/v1.0.0/MNLI.zip"
EXPECTED_TRAIN_MD5 = "df6dbc8cb3e3c76f6985fd0d327f01aa"
EXPECTED_ROWS = {"train.tsv": 392_702, "dev_matched.tsv": 9_815}
VALID_LABELS = {"entailment", "neutral", "contradiction"}
SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT = SCRIPT_DIR / "build" / "plue"


def digest(path: Path, algorithm: str) -> str:
    hasher = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def download(url: str, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".partial")
    if destination.exists():
        print(f"Using existing archive: {destination}")
        return

    print(f"Downloading {url}")
    request = urllib.request.Request(url, headers={"User-Agent": "Spike-9-PLUE-audit/1.0"})
    with urllib.request.urlopen(request, timeout=60) as response, partial.open("wb") as output:
        total = int(response.headers.get("Content-Length", "0"))
        copied = 0
        while True:
            block = response.read(1024 * 1024)
            if not block:
                break
            output.write(block)
            copied += len(block)
            if total:
                print(f"  {copied / 1024 / 1024:6.1f}/{total / 1024 / 1024:.1f} MiB", end="\r")
    print()
    partial.replace(destination)


def find_member(archive: zipfile.ZipFile, basename: str) -> str:
    matches = [name for name in archive.namelist() if Path(name).name == basename]
    if len(matches) != 1:
        raise RuntimeError(f"Expected exactly one {basename!r} in archive, found {matches}")
    return matches[0]


def extract_required(archive_path: Path, data_dir: Path) -> dict[str, str]:
    data_dir.mkdir(parents=True, exist_ok=True)
    members: dict[str, str] = {}
    with zipfile.ZipFile(archive_path) as archive:
        for basename in EXPECTED_ROWS:
            member = find_member(archive, basename)
            destination = data_dir / basename
            with archive.open(member) as source, destination.open("wb") as output:
                shutil.copyfileobj(source, output)
            members[basename] = member
    return members


def audit_tsv(path: Path) -> dict[str, object]:
    labels: Counter[str] = Counter()
    invalid_labels: Counter[str] = Counter()
    empty_sentence1 = 0
    empty_sentence2 = 0
    rows = 0
    unique_pairs: set[bytes] = set()
    duplicate_pairs = 0

    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"sentence1", "sentence2", "gold_label"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise RuntimeError(f"{path.name}: missing required columns: {sorted(missing)}")

        for row in reader:
            rows += 1
            premise = row["sentence1"].strip()
            hypothesis = row["sentence2"].strip()
            label = row["gold_label"].strip()
            if not premise:
                empty_sentence1 += 1
            if not hypothesis:
                empty_sentence2 += 1
            if label in VALID_LABELS:
                labels[label] += 1
            else:
                invalid_labels[label] += 1

            pair_hash = hashlib.blake2b(
                (premise + "\0" + hypothesis).encode("utf-8"), digest_size=16
            ).digest()
            if pair_hash in unique_pairs:
                duplicate_pairs += 1
            else:
                unique_pairs.add(pair_hash)

    return {
        "rows": rows,
        "labels": dict(sorted(labels.items())),
        "invalid_labels": dict(sorted(invalid_labels.items())),
        "empty_sentence1": empty_sentence1,
        "empty_sentence2": empty_sentence2,
        "duplicate_pairs": duplicate_pairs,
        "unique_pairs": len(unique_pairs),
        "md5": digest(path, "md5"),
        "sha256": digest(path, "sha256"),
        "bytes": path.stat().st_size,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--url", default=RELEASE_URL)
    args = parser.parse_args()

    output = args.output.resolve()
    archive_path = output / "MNLI.zip"
    data_dir = output / "MNLI"
    download(args.url, archive_path)

    if not zipfile.is_zipfile(archive_path):
        raise RuntimeError(f"Downloaded file is not a ZIP archive: {archive_path}")

    members = extract_required(archive_path, data_dir)
    files = {name: audit_tsv(data_dir / name) for name in EXPECTED_ROWS}
    failures: list[str] = []
    warnings: list[str] = []
    for name, expected_rows in EXPECTED_ROWS.items():
        observed_rows = int(files[name]["rows"])
        if observed_rows != expected_rows:
            failures.append(f"{name}: expected {expected_rows} rows, got {observed_rows}")
        if files[name]["invalid_labels"]:
            failures.append(f"{name}: invalid labels {files[name]['invalid_labels']}")
        empty_count = int(files[name]["empty_sentence1"]) + int(files[name]["empty_sentence2"])
        if empty_count:
            warnings.append(
                f"{name}: {empty_count} empty premise/hypothesis fields; training excludes these rows"
            )

    train_md5 = str(files["train.tsv"]["md5"])
    if train_md5 != EXPECTED_TRAIN_MD5:
        failures.append(f"train.tsv: expected MD5 {EXPECTED_TRAIN_MD5}, got {train_md5}")

    audit = {
        "source": {
            "dataset": "PLUE/MNLI",
            "release_url": args.url,
            "plue_repository_commit": "7603970b7aa43b91ce5f0841aa42e6770dd6369f",
            "language": "pt-BR (machine-translated MNLI)",
            "license": "LGPL-3.0",
            "label_order_for_training": {
                "0": "entailment",
                "1": "neutral",
                "2": "contradiction",
            },
        },
        "archive": {
            "path": str(archive_path),
            "bytes": archive_path.stat().st_size,
            "sha256": digest(archive_path, "sha256"),
            "members": members,
        },
        "files": files,
        "status": "PASS" if not failures else "FAIL",
        "failures": failures,
        "warnings": warnings,
    }
    audit_path = output / "dataset_audit.json"
    audit_path.write_text(json.dumps(audit, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(audit, ensure_ascii=False, indent=2))
    print(f"Audit written to {audit_path}")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
